---
- hosts: webservers
 # roles:
  #  - install_docker
  tasks:
     
     - name: install pip
       yum:
        name: python3-pip 
     - name: pip install docker
       pip:
        name: docker 
        version: 6.1.3

     - name: pip install docker
       pip:
        name: docker-compose
        

         
     - name: Copy file with owner and permissions
       ansible.builtin.copy:
        src: composetest
        dest: /opt/
    
     - name: Create and start services
       community.general.docker_compose:
         project_src: /opt/composetest
          
